categoryGroups:
  9daf7b14-27fe-44c5-a796-bd88508685be:
    handle: topicsTest
    name: 'Topics test'
    siteSettings:
      06419039-5941-41b4-a10b-a0003a4a0a8a:
        hasUrls: true
        template: ''
        uriFormat: 'topics-test/{slug}'
    structure:
      maxLevels: null
      uid: f86a74ca-7e91-4e78-8af6-452451af6d4a
dateModified: 1554229950
email:
  fromEmail: egiuse@andrew.cmu.edu
  fromName: Craft3manual
  template: ''
  transportSettings: null
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  7aec1807-48f2-41c7-b821-83a622e4258f:
    name: Topic/Subtopics
  bd49d05a-3814-4821-bcf9-2aedfed2e879:
    name: General
  e5d0e74d-dd9e-4ae9-b4b2-5e347b915e8f:
    name: Tags
  f9beb7ff-1bba-4e77-845f-8a92691f87a7:
    name: Homepage
fields:
  0e50d7a7-a7e6-44a5-93b4-c81eff229a26:
    contentColumnType: text
    fieldGroup: bd49d05a-3814-4821-bcf9-2aedfed2e879
    handle: shortDescription
    instructions: ''
    name: 'Short Description'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'Enter the the short description.'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2d6b8162-e845-4685-ab5e-97cb427833a1:
    contentColumnType: string
    fieldGroup: e5d0e74d-dd9e-4ae9-b4b2-5e347b915e8f
    handle: contentCategoryTagField
    instructions: ''
    name: 'Content Category Tag'
    searchable: true
    settings:
      limit: null
      localizeRelations: false
      selectionLabel: ''
      source: 'taggroup:f870fcf5-c00e-4116-8119-beb68daab851'
      sources: '*'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
  3520c4c3-1f26-49ea-bd54-ccfd77995a8c:
    contentColumnType: string
    fieldGroup: e5d0e74d-dd9e-4ae9-b4b2-5e347b915e8f
    handle: institutionTagField
    instructions: ''
    name: 'Institution Tag'
    searchable: true
    settings:
      limit: null
      localizeRelations: false
      selectionLabel: ''
      source: 'taggroup:3cf0a51d-6681-4ef9-a9d2-827f9e0ed36a'
      sources: '*'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
  4e8f10fd-629a-44d9-a227-a25cd1e0cdd1:
    contentColumnType: string
    fieldGroup: e5d0e74d-dd9e-4ae9-b4b2-5e347b915e8f
    handle: locationStateTagField
    instructions: ''
    name: 'Location State Tag'
    searchable: true
    settings:
      limit: null
      localizeRelations: false
      selectionLabel: ''
      source: 'taggroup:5fd43216-4949-46d6-a2c5-07b661977ab1'
      sources: '*'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
  5859f2ae-a21b-45b2-8f44-f8e7a8fefd31:
    contentColumnType: string
    fieldGroup: f9beb7ff-1bba-4e77-845f-8a92691f87a7
    handle: clientlogos
    instructions: ''
    name: clientLogos
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: ''
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      singleUploadLocationSource: ''
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  820ecbe8-2ac2-4a00-84a9-dd4a5331d6fe:
    contentColumnType: string
    fieldGroup: 7aec1807-48f2-41c7-b821-83a622e4258f
    handle: documentTagsField
    instructions: ''
    name: 'Document Tags'
    searchable: true
    settings:
      columns:
        29:
          width: ''
        30:
          width: ''
        31:
          width: ''
        32:
          width: ''
      contentTable: '{{%stc_documenttagsfield}}'
      fieldLayout: row
      localizeBlocks: false
      maxRows: ''
      minRows: ''
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a45974e5-3976-47ad-8022-b97e2e2b7e46:
    contentColumnType: text
    fieldGroup: bd49d05a-3814-4821-bcf9-2aedfed2e879
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'This will show at the top of the page.'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  af0c2fba-82a5-4eb5-860f-606d34e9ee17:
    contentColumnType: string
    fieldGroup: 7aec1807-48f2-41c7-b821-83a622e4258f
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:14a5170c-9eed-42d3-a7e7-103749b44e85'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: 'Choose an icon.'
      singleUploadLocationSource: 'volume:af5d9f4c-8370-4936-b18f-2656c9900a8d'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:14a5170c-9eed-42d3-a7e7-103749b44e85'
      targetSiteId: null
      useSingleFolder: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b782df66-c05d-4de6-be7b-963cc07585d5:
    contentColumnType: text
    fieldGroup: bd49d05a-3814-4821-bcf9-2aedfed2e879
    handle: slogan
    instructions: ''
    name: Slogan
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'Enter the slogan'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f9540f2f-94dc-4496-bb78-51b9dde2a76f:
    contentColumnType: string
    fieldGroup: 7aec1807-48f2-41c7-b821-83a622e4258f
    handle: documents
    instructions: 'After adding an asset, double click on it for its information.'
    name: Documents
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:c9fb2884-b316-47b8-8ee1-8c13739b99cb'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      singleUploadLocationSource: 'volume:c9fb2884-b316-47b8-8ee1-8c13739b99cb'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:c9fb2884-b316-47b8-8ee1-8c13739b99cb'
      targetSiteId: null
      useSingleFolder: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fc50edbb-828e-4f6e-96a2-2f1e988d8ee9:
    contentColumnType: string
    fieldGroup: e5d0e74d-dd9e-4ae9-b4b2-5e347b915e8f
    handle: fileTypeTagField
    instructions: ''
    name: 'File Type Tag'
    searchable: true
    settings:
      limit: null
      localizeRelations: false
      selectionLabel: ''
      source: 'taggroup:d9eafeb5-1a3b-41cd-9ca3-6f880f1a131d'
      sources: '*'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
plugins:
  child-me:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cpSectionEnabled: ''
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.2.2
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.0.10
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  3323900d-bc90-4c77-8638-89fe3d9baaa1:
    enableVersioning: true
    entryTypes:
      d28dcdf2-fece-4f08-8997-be4605045f0d:
        fieldLayouts:
          4711eda5-f6b1-4a0f-9292-752e23d80424:
            tabs:
              -
                fields:
                  a45974e5-3976-47ad-8022-b97e2e2b7e46:
                    required: true
                    sortOrder: 1
                name: Content
                sortOrder: 1
        handle: home
        hasTitleField: true
        name: Home
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: Title
    handle: home
    name: Home
    propagateEntries: true
    siteSettings:
      06419039-5941-41b4-a10b-a0003a4a0a8a:
        enabledByDefault: true
        hasUrls: true
        template: home
        uriFormat: __home__
    type: single
  467a7187-2226-4c46-bcc4-3b390493f66a:
    enableVersioning: true
    entryTypes:
      f73d5627-97e9-4ce2-8239-72feadd13639:
        fieldLayouts:
          88d9e27f-a3e2-406f-b2ef-47da2f72ed51:
            tabs:
              -
                fields:
                  a45974e5-3976-47ad-8022-b97e2e2b7e46:
                    required: true
                    sortOrder: 1
                name: Content
                sortOrder: 1
        handle: topicsIndex
        hasTitleField: true
        name: 'Topics Index'
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: 'Topics Index'
    handle: topicsIndex
    name: 'Topics Index'
    propagateEntries: true
    siteSettings:
      06419039-5941-41b4-a10b-a0003a4a0a8a:
        enabledByDefault: true
        hasUrls: true
        template: topics_index
        uriFormat: /topics
    type: single
  6bf6ecfb-cd83-47f9-8c99-d75b4e1b9b89:
    enableVersioning: true
    entryTypes:
      ad1814ea-c8e3-4ce8-bcc8-f017f3f3bc45:
        fieldLayouts:
          64cd9903-ea4f-469a-a59d-b6721a893839:
            tabs:
              -
                fields:
                  a45974e5-3976-47ad-8022-b97e2e2b7e46:
                    required: true
                    sortOrder: 1
                name: Content
                sortOrder: 1
        handle: about
        hasTitleField: false
        name: About
        sortOrder: 1
        titleFormat: About
        titleLabel: Title
    handle: about
    name: About
    propagateEntries: true
    siteSettings:
      06419039-5941-41b4-a10b-a0003a4a0a8a:
        enabledByDefault: true
        hasUrls: true
        template: about
        uriFormat: /about
    type: single
  c469a882-e929-4b33-9e7b-bea1c720755e:
    enableVersioning: true
    entryTypes:
      729cad62-7474-495f-bd45-7de8bb49f42d:
        fieldLayouts:
          0eeebb26-5582-45bc-94b8-c53afd5dec24:
            tabs:
              -
                fields:
                  0e50d7a7-a7e6-44a5-93b4-c81eff229a26:
                    required: false
                    sortOrder: 3
                  a45974e5-3976-47ad-8022-b97e2e2b7e46:
                    required: true
                    sortOrder: 1
                  af0c2fba-82a5-4eb5-860f-606d34e9ee17:
                    required: false
                    sortOrder: 2
                  b782df66-c05d-4de6-be7b-963cc07585d5:
                    required: false
                    sortOrder: 4
                  f9540f2f-94dc-4496-bb78-51b9dde2a76f:
                    required: false
                    sortOrder: 5
                name: Content
                sortOrder: 1
        handle: topics_entry_type
        hasTitleField: true
        name: topics_entry_type
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: topics_section
    name: 'Topics Entries'
    propagateEntries: true
    siteSettings:
      06419039-5941-41b4-a10b-a0003a4a0a8a:
        enabledByDefault: true
        hasUrls: true
        template: topic_show
        uriFormat: '{parent.uri}/{slug}'
    structure:
      maxLevels: ''
      uid: 1cdb4495-063e-48df-b0e9-31f4b275d062
    type: structure
siteGroups:
  36f6937e-673b-4f31-845c-d37b7f19de90:
    name: Craft3manual
sites:
  06419039-5941-41b4-a10b-a0003a4a0a8a:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Craft3manual
    primary: true
    siteGroup: 36f6937e-673b-4f31-845c-d37b7f19de90
    sortOrder: 1
superTableBlockTypes:
  b87e3609-07d3-4f8d-b014-02d43c1b7e6b:
    field: 820ecbe8-2ac2-4a00-84a9-dd4a5331d6fe
    fieldLayouts:
      6185ca10-51a0-432f-bbc2-44ec6ed400ab:
        tabs:
          -
            fields:
              2a23569a-a1d0-4191-bed6-fc858f3b4bb2:
                required: true
                sortOrder: 1
              481a06cd-7b7b-4896-b424-92f974707d75:
                required: false
                sortOrder: 4
              81a65cb5-3e61-4703-9956-f476c8a6ea05:
                required: false
                sortOrder: 2
              94cc11fa-8674-4f16-a557-280a339f59f8:
                required: false
                sortOrder: 3
            name: Content
            sortOrder: 1
    fields:
      2a23569a-a1d0-4191-bed6-fc858f3b4bb2:
        contentColumnType: string
        fieldGroup: null
        handle: stateTagField
        instructions: ''
        name: 'State Tag'
        searchable: true
        settings:
          limit: null
          localizeRelations: false
          selectionLabel: ''
          source: 'taggroup:5fd43216-4949-46d6-a2c5-07b661977ab1'
          sources: '*'
          targetSiteId: null
          viewMode: null
        translationKeyFormat: null
        translationMethod: site
        type: craft\fields\Tags
      481a06cd-7b7b-4896-b424-92f974707d75:
        contentColumnType: string
        fieldGroup: null
        handle: institutionTagField
        instructions: ''
        name: 'Institution Tag'
        searchable: true
        settings:
          limit: null
          localizeRelations: false
          selectionLabel: ''
          source: 'taggroup:3cf0a51d-6681-4ef9-a9d2-827f9e0ed36a'
          sources: '*'
          targetSiteId: null
          viewMode: null
        translationKeyFormat: null
        translationMethod: site
        type: craft\fields\Tags
      81a65cb5-3e61-4703-9956-f476c8a6ea05:
        contentColumnType: string
        fieldGroup: null
        handle: contentTagField
        instructions: ''
        name: 'Content Tag'
        searchable: true
        settings:
          limit: null
          localizeRelations: false
          selectionLabel: ''
          source: 'taggroup:f870fcf5-c00e-4116-8119-beb68daab851'
          sources: '*'
          targetSiteId: null
          viewMode: null
        translationKeyFormat: null
        translationMethod: site
        type: craft\fields\Tags
      94cc11fa-8674-4f16-a557-280a339f59f8:
        contentColumnType: string
        fieldGroup: null
        handle: fileTypeTagField
        instructions: ''
        name: 'File Type Tag'
        searchable: true
        settings:
          limit: null
          localizeRelations: false
          selectionLabel: ''
          source: 'taggroup:d9eafeb5-1a3b-41cd-9ca3-6f880f1a131d'
          sources: '*'
          targetSiteId: null
          viewMode: null
        translationKeyFormat: null
        translationMethod: site
        type: craft\fields\Tags
system:
  edition: pro
  live: true
  name: 'AACI Library'
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
tagGroups:
  3cf0a51d-6681-4ef9-a9d2-827f9e0ed36a:
    handle: institution
    name: Institution
  5fd43216-4949-46d6-a2c5-07b661977ab1:
    handle: documentState
    name: State
  d9eafeb5-1a3b-41cd-9ca3-6f880f1a131d:
    fieldLayouts:
      14f2db13-e780-4939-a8d5-1d352f62dce9:
        tabs:
          -
            fields:
              0e50d7a7-a7e6-44a5-93b4-c81eff229a26:
                required: false
                sortOrder: 1
            name: Content
            sortOrder: 1
    handle: fileType
    name: 'File Type'
  f2cd8507-090e-414c-b6ea-fb24c7120ee9:
    handle: documentTitle
    name: Title
  f870fcf5-c00e-4116-8119-beb68daab851:
    handle: documentContent
    name: Content
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  14a5170c-9eed-42d3-a7e7-103749b44e85:
    handle: subtopicIcons
    hasUrls: false
    name: 'Subtopic Icons'
    settings:
      path: '@webroot/assets/images/subtopic-icons'
    sortOrder: 2
    type: craft\volumes\Local
    url: ''
  af5d9f4c-8370-4936-b18f-2656c9900a8d:
    fieldLayouts:
      24338092-df26-48b3-8f9c-fa9416f26b27:
        tabs:
          -
            name: Content
            sortOrder: 1
    handle: topicIcons
    hasUrls: false
    name: 'Topic Icons'
    settings:
      path: '@webroot/assets/images/topic-icons'
    sortOrder: '1'
    type: craft\volumes\Local
    url: ''
  c9fb2884-b316-47b8-8ee1-8c13739b99cb:
    fieldLayouts:
      4e5a5859-199e-4487-af13-9869b3a713d2:
        tabs:
          -
            fields:
              0e50d7a7-a7e6-44a5-93b4-c81eff229a26:
                required: false
                sortOrder: 1
              820ecbe8-2ac2-4a00-84a9-dd4a5331d6fe:
                required: false
                sortOrder: 2
            name: Content
            sortOrder: 1
    handle: resources
    hasUrls: false
    name: Resources
    settings:
      path: '@webroot/assets/resources'
    sortOrder: '7'
    type: craft\volumes\Local
    url: ''
